### ISSUE TITLE
Are the stopwords intentionally quoted?

### ISSUE THREAD

**Issue by ryanavella** [cmccomb/rust-stop-words#2]
`stop_words::get` returns a `Vec<String>`, however the strings are all quoted so I frequently find myself calling it like this.

```rust
let words = stop_words::get(stop_words::LANGUAGE::English)
        .into_iter()
        .map(|s| s.trim_matches('"').to_owned())
        .collect::<HashSet<_>>();
```

Is this intentional? If so I'm thinking this could be documented a little better along with a rationale, but I suspect this may just be a bug?

**Comment by cmccomb** [comment]
Thanks for catching the bug! I just made some changes to correct that and added some additional tests as well. I'm pushing `v0.8.1` to Cargo right now.
